from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Protocol, runtime_checkable

from minimal_harness.memory_store import SessionStoreProtocol


def _ts_ms() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"


@runtime_checkable
class DatabaseProtocol(Protocol):
    async def init(self, dsn: str) -> None: ...
    async def close(self) -> None: ...
    async def init_schema(self) -> None: ...
    async def create_session_store(self) -> SessionStoreProtocol: ...
    async def execute(self, sql: str, params: list | None = None) -> Any: ...
    async def execute_write(self, sql: str, params: list | None = None) -> int: ...
    async def execute_many_write(self, sql: str, params_list: list[list]) -> None: ...
    async def fetch_one(self, sql: str, params: list | None = None) -> dict | None: ...
    async def fetch_all(self, sql: str, params: list | None = None) -> list[dict]: ...
    async def begin(self) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
    async def executemany(self, sql: str, params_list: list[list]) -> None: ...


class _CursorWrapper:
    def __init__(self, rowcount: int = 0) -> None:
        self.rowcount = rowcount
